THIS IS NO LONGER IN USE!! This notebook was used to test and teach. We decided to stop using pandas dataframes to populate the database and instead moved to SQLite to do this. We also moved to using SQL alchemy for creating the tables.

This first box will create the database. It creates the database if one doesn't exist and recreates it if it does exist.

In [ ]:
import sqlite3
import pandas as pd
import os

DB_PATH = "travel.db"

if os.path.exists(DB_PATH):
    os.remove(DB_PATH)

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

cursor.execute("PRAGMA foreign_keys = ON;")

This next box will create tables with raw SQL

In [3]:
cursor.execute("""
CREATE TABLE countries (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    region TEXT,
    currency_code TEXT,
    main_language TEXT
);
""")

cursor.execute("""
CREATE TABLE destinations (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    country_id INTEGER NOT NULL,
    destination_type TEXT,

    FOREIGN KEY (country_id) REFERENCES countries(id),
    UNIQUE(name, country_id)
);
""")

cursor.execute("""
CREATE TABLE cost_profiles (
    id INTEGER PRIMARY KEY,
    destination_id INTEGER NOT NULL UNIQUE,
    budget_level TEXT,

    FOREIGN KEY (destination_id) REFERENCES destinations(id)
);
""")

cursor.execute("""
CREATE TABLE weather_monthly (
    id INTEGER PRIMARY KEY,
    destination_id INTEGER NOT NULL,
    month INTEGER NOT NULL,
    avg_temp_c REAL,
    rainfall_mm REAL,

    FOREIGN KEY (destination_id) REFERENCES destinations(id),
    UNIQUE(destination_id, month)
);
""")

cursor.execute("""
CREATE TABLE activity_types (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);
""")

cursor.execute("""
CREATE TABLE activities (
    id INTEGER PRIMARY KEY,
    destination_id INTEGER NOT NULL,
    activity_type_id INTEGER NOT NULL,
    activity_name TEXT,

    FOREIGN KEY (destination_id) REFERENCES destinations(id),
    FOREIGN KEY (activity_type_id) REFERENCES activity_types(id)
);
""")


cursor.execute("""
CREATE TABLE travel_vibes (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);
""")

cursor.execute("""
CREATE TABLE destination_vibes (
    destination_id INTEGER NOT NULL,
    vibe_id INTEGER NOT NULL,

    FOREIGN KEY (destination_id) REFERENCES destinations(id),
    FOREIGN KEY (vibe_id) REFERENCES travel_vibes(id),
    PRIMARY KEY (destination_id, vibe_id)
);
""")

conn.commit()

The next boxes will use pandas DataFrames to seed the tables. This first one is for countries

In [4]:
import pandas as pd

countries_df = pd.DataFrame([
    {
        "id": 1,
        "name": "Portugal",
        "region": "Europe",
        "currency_code": "EUR",
        "main_language": "Portuguese"
    },
    {
        "id": 2,
        "name": "Spain",
        "region": "Europe",
        "currency_code": "EUR",
        "main_language": "Spanish"
    },
    {
        "id": 3,
        "name": "Italy",
        "region": "Europe",
        "currency_code": "EUR",
        "main_language": "Italian"
    },
    {
        "id": 4,
        "name": "France",
        "region": "Europe",
        "currency_code": "EUR",
        "main_language": "French"
    },
    {
        "id": 5,
        "name": "Germany",
        "region": "Europe",
        "currency_code": "EUR",
        "main_language": "German"
    },
    {
        "id": 6,
        "name": "Netherlands",
        "region": "Europe",
        "currency_code": "EUR",
        "main_language": "Dutch"
    },
    {
        "id": 7,
        "name": "Greece",
        "region": "Europe",
        "currency_code": "EUR",
        "main_language": "Greek"
    },
    {
        "id": 8,
        "name": "Croatia",
        "region": "Europe",
        "currency_code": "EUR",
        "main_language": "Croatian"
    },
    {
        "id": 9,
        "name": "United Kingdom",
        "region": "Europe",
        "currency_code": "GBP",
        "main_language": "English"
    },
    {
        "id": 10,
        "name": "Turkey",
        "region": "Europe/Asia",
        "currency_code": "TRY",
        "main_language": "Turkish"
    }
])  

countries_df.to_sql("countries", conn, if_exists="append", index=False)

10

This next one is for destinations in those countries

In [5]:
destinations_df = pd.DataFrame([
    {
        "id": 1,
        "name": "Lisbon",
        "country_id": 1,
        "destination_type": "city"
    },
    {
        "id": 2,
        "name": "Barcelona",
        "country_id": 2,
        "destination_type": "city"
    },
    {
        "id": 3,
        "name": "Rome",
        "country_id": 3,
        "destination_type": "city"
    },
    {
        "id": 4,
        "name": "Paris",
        "country_id": 4,
        "destination_type": "city"
    },
    {
        "id": 5,
        "name": "Berlin",
        "country_id": 5,
        "destination_type": "city"
    },
    {
        "id": 6,
        "name": "Amsterdam",
        "country_id": 6,
        "destination_type": "city"
    },
    {
        "id": 7,
        "name": "Athens",
        "country_id": 7,
        "destination_type": "city"
    },
    {
        "id": 8,
        "name": "Dubrovnik",
        "country_id": 8,
        "destination_type": "coastal city"
    },
    {
        "id": 9,
        "name": "Edinburgh",
        "country_id": 9,
        "destination_type": "city"
    },
    {
        "id": 10,
        "name": "Istanbul",
        "country_id": 10,
        "destination_type": "city"
    }
])

destinations_df.to_sql("destinations", conn, if_exists="append", index=False)

10

next one for cost

In [6]:
cost_profiles_df = pd.DataFrame([
    {
        "id": 1,
        "destination_id": 1,
        "budget_level": "medium"
    },
    {
        "id": 2,
        "destination_id": 2,
        "budget_level": "medium"
    },
    {
        "id": 3,
        "destination_id": 3,
        "budget_level": "medium"
    },
    {
        "id": 4,
        "destination_id": 4,
        "budget_level": "expensive"
    },
    {
        "id": 5,
        "destination_id": 5,
        "budget_level": "medium"
    },
    {
        "id": 6,
        "destination_id": 6,
        "budget_level": "expensive"
    },
    {
        "id": 7,
        "destination_id": 7,
        "budget_level": "cheap"
    },
    {
        "id": 8,
        "destination_id": 8,
        "budget_level": "medium"
    },
    {
        "id": 9,
        "destination_id": 9,
        "budget_level": "medium"
    },
    {
        "id": 10,
        "destination_id": 10,
        "budget_level": "cheap"
    }
])

cost_profiles_df.to_sql("cost_profiles", conn, if_exists="append", index=False)

10

next one for weather

In [7]:
weather_monthly_df = pd.DataFrame([
    {
        "id": 1,
        "destination_id": 1,
        "month": 7,
        "avg_temp_c": 24.5,
        "rainfall_mm": 6.0
    },
    {
        "id": 2,
        "destination_id": 2,
        "month": 7,
        "avg_temp_c": 26.0,
        "rainfall_mm": 20.0
    },
    {
        "id": 3,
        "destination_id": 3,
        "month": 7,
        "avg_temp_c": 27.0,
        "rainfall_mm": 15.0
    },
    {
        "id": 4,
        "destination_id": 4,
        "month": 7,
        "avg_temp_c": 21.0,
        "rainfall_mm": 55.0
    },
    {
        "id": 5,
        "destination_id": 5,
        "month": 7,
        "avg_temp_c": 19.0,
        "rainfall_mm": 70.0
    },
    {
        "id": 6,
        "destination_id": 6,
        "month": 7,
        "avg_temp_c": 18.5,
        "rainfall_mm": 75.0
    },
    {
        "id": 7,
        "destination_id": 7,
        "month": 7,
        "avg_temp_c": 28.5,
        "rainfall_mm": 6.0
    },
    {
        "id": 8,
        "destination_id": 8,
        "month": 7,
        "avg_temp_c": 26.5,
        "rainfall_mm": 26.0
    },
    {
        "id": 9,
        "destination_id": 9,
        "month": 7,
        "avg_temp_c": 15.5,
        "rainfall_mm": 65.0
    },
    {
        "id": 10,
        "destination_id": 10,
        "month": 7,
        "avg_temp_c": 25.5,
        "rainfall_mm": 25.0
    }
])

weather_monthly_df.to_sql("weather_monthly", conn, if_exists="append", index=False)

10

activity types!

In [8]:
activity_types_df = pd.DataFrame([
    {
        "id": 1,
        "name": "beach"
    },
    {
        "id": 2,
        "name": "history"
    },
    {
        "id": 3,
        "name": "food"
    },
    {
        "id": 4,
        "name": "nightlife"
    },
    {
        "id": 5,
        "name": "shopping"
    },
    {
        "id": 6,
        "name": "nature"
    },
    {
        "id": 7,
        "name": "art"
    },
    {
        "id": 8,
        "name": "architecture"
    },
    {
        "id": 9,
        "name": "family"
    },
    {
        "id": 10,
        "name": "outdoor"
    }
])

activity_types_df.to_sql("activity_types", conn, if_exists="append", index=False)

10

and activities

In [9]:
activities_df = pd.DataFrame([
    {
        "id": 1,
        "destination_id": 1,
        "activity_type_id": 2,
        "activity_name": "Explore Alfama and historic Lisbon"
    },
    {
        "id": 2,
        "destination_id": 2,
        "activity_type_id": 1,
        "activity_name": "Visit Barceloneta Beach"
    },
    {
        "id": 3,
        "destination_id": 3,
        "activity_type_id": 2,
        "activity_name": "Visit the Colosseum"
    },
    {
        "id": 4,
        "destination_id": 4,
        "activity_type_id": 7,
        "activity_name": "Visit the Louvre Museum"
    },
    {
        "id": 5,
        "destination_id": 5,
        "activity_type_id": 2,
        "activity_name": "See the Berlin Wall Memorial"
    },
    {
        "id": 6,
        "destination_id": 6,
        "activity_type_id": 7,
        "activity_name": "Visit the Van Gogh Museum"
    },
    {
        "id": 7,
        "destination_id": 7,
        "activity_type_id": 2,
        "activity_name": "Visit the Acropolis"
    },
    {
        "id": 8,
        "destination_id": 8,
        "activity_type_id": 1,
        "activity_name": "Walk along the Dubrovnik coastline"
    },
    {
        "id": 9,
        "destination_id": 9,
        "activity_type_id": 2,
        "activity_name": "Explore Edinburgh Castle"
    },
    {
        "id": 10,
        "destination_id": 10,
        "activity_type_id": 8,
        "activity_name": "Visit Hagia Sophia"
    }
])

activities_df.to_sql("activities", conn, if_exists="append", index=False)

10

and travel vibes from the updater notebook concepts

In [10]:
travel_vibes_df = pd.DataFrame([
    {"id": 1, "name": "Frugal Adventure"},
    {"id": 2, "name": "Sun & Sand"},
    {"id": 3, "name": "Nautical Luxury"},
    {"id": 4, "name": "Open Road"},
    {"id": 5, "name": "Rustic Wilderness"},
    {"id": 6, "name": "Alpine Thrills"},
    {"id": 7, "name": "Urban Explorer"},
    {"id": 8, "name": "Pure Relaxation"},
    {"id": 9, "name": "Gastronomic Journey"},
    {"id": 10, "name": "Cultural Roots"}
])

travel_vibes_df.to_sql("travel_vibes", conn, if_exists="append", index=False)

destination_vibes_df = pd.DataFrame([
    {"destination_id": 1, "vibe_id": 7},
    {"destination_id": 1, "vibe_id": 9},
    {"destination_id": 2, "vibe_id": 2},
    {"destination_id": 2, "vibe_id": 9},
    {"destination_id": 3, "vibe_id": 9},
    {"destination_id": 3, "vibe_id": 10},
    {"destination_id": 4, "vibe_id": 9},
    {"destination_id": 4, "vibe_id": 10},
    {"destination_id": 5, "vibe_id": 7},
    {"destination_id": 5, "vibe_id": 10},
    {"destination_id": 6, "vibe_id": 7},
    {"destination_id": 6, "vibe_id": 8},
    {"destination_id": 7, "vibe_id": 1},
    {"destination_id": 7, "vibe_id": 10},
    {"destination_id": 8, "vibe_id": 2},
    {"destination_id": 8, "vibe_id": 8},
    {"destination_id": 9, "vibe_id": 5},
    {"destination_id": 9, "vibe_id": 10},
    {"destination_id": 10, "vibe_id": 9},
    {"destination_id": 10, "vibe_id": 10}
])

destination_vibes_df.to_sql("destination_vibes", conn, if_exists="append", index=False)

20

Now that all the tables are populated with "fake" data we can query it with SQL to make sure everything is working. This first one checks all tables were created.

In [11]:
query = """
SELECT name
FROM sqlite_master
WHERE type = 'table';
"""

pd.read_sql_query(query, conn)

                name
0          countries
1       destinations
2      cost_profiles
3    weather_monthly
4     activity_types
5         activities
6       travel_vibes
7  destination_vibes

This one checks the columns, data types, and primary key for destinations

In [ ]:
query = """
PRAGMA table_info(destinations);
"""
pd.read_sql_query(query, conn)

   cid              name     type  notnull dflt_value  pk
0    0                id  INTEGER        0       None   1
1    1              name     TEXT        1       None   0
2    2        country_id  INTEGER        1       None   0
3    3  destination_type     TEXT        0       None   0

check if countries work

In [ ]:
query = """
SELECT *
FROM countries;
"""

pd.read_sql_query(query, conn)

   id            name       region currency_code main_language
0   1        Portugal       Europe           EUR    Portuguese
1   2           Spain       Europe           EUR       Spanish
2   3           Italy       Europe           EUR       Italian
3   4          France       Europe           EUR        French
4   5         Germany       Europe           EUR        German
5   6     Netherlands       Europe           EUR         Dutch
6   7          Greece       Europe           EUR         Greek
7   8         Croatia       Europe           EUR      Croatian
8   9  United Kingdom       Europe           GBP       English
9  10          Turkey  Europe/Asia           TRY       Turkish

Checks that activities link correctly to both destinations and activity types.

In [ ]:
query = """
SELECT
    destinations.name AS destination,
    activity_types.name AS activity_type,
    activities.activity_name
FROM activities
JOIN destinations
    ON activities.destination_id = destinations.id
JOIN activity_types
    ON activities.activity_type_id = activity_types.id;
"""

pd.read_sql_query(query, conn)

  destination activity_type                       activity_name
0      Lisbon       history  Explore Alfama and historic Lisbon
1   Barcelona         beach             Visit Barceloneta Beach
2        Rome       history                 Visit the Colosseum
3       Paris           art             Visit the Louvre Museum
4      Berlin       history        See the Berlin Wall Memorial
5   Amsterdam           art           Visit the Van Gogh Museum
6      Athens       history                 Visit the Acropolis
7   Dubrovnik         beach  Walk along the Dubrovnik coastline
8   Edinburgh       history            Explore Edinburgh Castle
9    Istanbul  architecture                  Visit Hagia Sophia

Now we can test some basic filtering:

In [ ]:
query = """
SELECT
    destinations.name AS destination,
    countries.name AS country,
    cost_profiles.budget_level
FROM destinations
JOIN countries
    ON destinations.country_id = countries.id
JOIN cost_profiles
    ON destinations.id = cost_profiles.destination_id
WHERE cost_profiles.budget_level = 'cheap';
"""

pd.read_sql_query(query, conn)

  destination country budget_level
0      Athens  Greece        cheap
1    Istanbul  Turkey        cheap

Finally a test of a full query that we could use for the front-end:

In [ ]:
query = """
SELECT DISTINCT
    destinations.name AS destination,
    countries.name AS country,
    cost_profiles.budget_level,
    weather_monthly.avg_temp_c,
    activity_types.name AS activity_type
FROM destinations
JOIN countries
    ON destinations.country_id = countries.id
JOIN cost_profiles
    ON destinations.id = cost_profiles.destination_id
JOIN weather_monthly
    ON destinations.id = weather_monthly.destination_id
JOIN activities
    ON destinations.id = activities.destination_id
JOIN activity_types
    ON activities.activity_type_id = activity_types.id
WHERE cost_profiles.budget_level = 'cheap'
AND weather_monthly.month = 7
AND weather_monthly.avg_temp_c >= 25;
"""

pd.read_sql_query(query, conn)

  destination country budget_level  avg_temp_c activity_type
0      Athens  Greece        cheap        28.5       history
1    Istanbul  Turkey        cheap        25.5  architecture